name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup

      - name: Setup npm registry
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
        
      - name: Run linting
        run: npm run lint
        
      - name: Check TypeScript compilation
        run: npm run type-check
        
      - name: Check code formatting
        run: npm run format:check
        
      - name: Run tests
        run: npm test -- --coverage
        
      - name: Build package
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 30

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
